### ISSUE TITLE
Issues with Breath of the Wild Graphic Packs

### ISSUE THREAD

**Issue by Crementif** [slashiee/gfx_pack#7]
Feel free to help us by commenting newly found issues if you find any.
If it's at a specific point in the game (like a final boss or something), providing a save file will help.

Currently known issues:

- [x] Bomb Texture
- [x] Shadow Pack for 1.14.0
- [x] Heatwaves
- [x] Bloom has a variety of problems

**Comment by getdls** [comment]
This one "passes" most of the wak-up link intro.  Bloom is scaled (first 3 levels at least) , light sources and cinematic DOF.  There are rules in place for the rest of the bloom/depth , but they need separate verification so they don't break other stuff.  esp all the cube/light grading

[BreathOfTheWild.zip](https://github.com/slashiee/gfx_pack/files/2308194/BreathOfTheWild.zip)

Also spent waay too long time before I figured out that the "fog" of the opening scene is broken due to cemu, not gfx pack..

**Comment by Crementif** [comment]
Hm, I've already found out some of the issues above (like the bloom). Haven't look at the link intro yet, so I'll add those related lines.

**Comment by Crementif** [comment]
This issue has become pretty outdated since SkalFate took BotW over. None of the problems mentioned are a problem. If there's any more problems, make a new thread.
